
name: GBA ROM Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with devkitARM Docker
        run: |
          docker run --rm -v "$PWD:/work" -w /work devkitpro/devkitarm:20240701 make

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: faunafrontier-gba
          path: faunafrontier.gba
